/**
 * facturacion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Article from './Article';

/**
 * The Inventory model module.
 * @module model/Inventory
 * @version 1.0
 */
class Inventory {
    /**
     * Constructs a new <code>Inventory</code>.
     * @alias module:model/Inventory
     * @param name {String} 
     */
    constructor(name) { 
        
        Inventory.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Inventory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Inventory} obj Optional instance to populate.
     * @return {module:model/Inventory} The populated <code>Inventory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Inventory();

            if (data.hasOwnProperty('inventoryId')) {
                obj['inventoryId'] = ApiClient.convertToType(data['inventoryId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('articles')) {
                obj['articles'] = ApiClient.convertToType(data['articles'], [Article]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Inventory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Inventory</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Inventory.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['inventoryId'] && !(typeof data['inventoryId'] === 'string' || data['inventoryId'] instanceof String)) {
            throw new Error("Expected the field `inventoryId` to be a primitive type in the JSON string but got " + data['inventoryId']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['articles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['articles'])) {
                throw new Error("Expected the field `articles` to be an array in the JSON data but got " + data['articles']);
            }
            // validate the optional field `articles` (array)
            for (const item of data['articles']) {
                Article.validateJSON(item);
            };
        }

        return true;
    }


}

Inventory.RequiredProperties = ["name"];

/**
 * @member {String} inventoryId
 */
Inventory.prototype['inventoryId'] = undefined;

/**
 * @member {String} name
 */
Inventory.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Article>} articles
 */
Inventory.prototype['articles'] = undefined;






export default Inventory;

